### ISSUE TITLE
Add into_vec method and split_off_by_index.

### ISSUE THREAD

**Issue by heckad** [facebookexperimental/rust-shed#11]
I have a `orders: SortedVectorMap<Price, Bucket>`. Each bucket has an amount. I want to take first buckets while they amount sum less than some amount and split on two SortedVectorMap and convert one of them to `Vec<Price, Bucket>`. This requires two methods: into_vec(for convert to vec) and (split_off_by_index for splitting by position which I got from position method in an iterator). Please add this method. Thank you.

**Comment by lukaspiatkowski** [comment]
There is already a `split_off ` method here: https://github.com/facebookexperimental/rust-shed/blob/19dff9fb3f349ed60d0dff9dcfc4103f3708b44d/shed/sorted_vector_map/src/map.rs#L264 and there is a `IntoIterator` implementation, so you can change your `SortedVectorMap` into iterator and then collect it into a `Vec`. I hope that this helps.

**Comment by heckad** [comment]
1) `split_off` splits by key, not by index. 
2) Is this exactly optimal?

**Comment by lukaspiatkowski** [comment]
about 1) Depending on your use case you can use the index to get the key
and use it for splitting. You could also change all to iterator, split it
using iterator methods and then build it up again from the iterator.

about 2) Whether it is optimal again depends on your use case, e.g. if you
want to create a Vec out of the first part or the second part of the split,
but I think that Rust should handle this well. Also doing it through
iterator is more flexible (as you can create other data types out of it).

**Comment by heckad** [comment]
1) When creating a SortedVectorMap from the second iterator, wouldn't I have any additional check(for example check ordering)?
2) I'll try this.
